// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCekBTTMFW9-EBGW0dLIoxEeb6NEPLKoOU',
    appId: '1:1043259362773:web:fdc931b0d831f6e682415c',
    messagingSenderId: '1043259362773',
    projectId: 'sanberapp-54',
    authDomain: 'sanberapp-54.firebaseapp.com',
    storageBucket: 'sanberapp-54.appspot.com',
    measurementId: 'G-FW55Z3Q0E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLZnxu6GLHi9EgR3z8glzQxsVxI6jleq8',
    appId: '1:1043259362773:android:6d774cfa5d1092b782415c',
    messagingSenderId: '1043259362773',
    projectId: 'sanberapp-54',
    storageBucket: 'sanberapp-54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMGZDYDiuGmxTG-2FGh5fEfSeEBCZm6eE',
    appId: '1:1043259362773:ios:ac32a3670a24ae0a82415c',
    messagingSenderId: '1043259362773',
    projectId: 'sanberapp-54',
    storageBucket: 'sanberapp-54.appspot.com',
    iosBundleId: 'com.example.integrationFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMGZDYDiuGmxTG-2FGh5fEfSeEBCZm6eE',
    appId: '1:1043259362773:ios:0a1ba7a620d2b59e82415c',
    messagingSenderId: '1043259362773',
    projectId: 'sanberapp-54',
    storageBucket: 'sanberapp-54.appspot.com',
    iosBundleId: 'com.example.integrationFirebaseApp.RunnerTests',
  );
}
